default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

development:
  <<: *default
  database: scores_dev_db

production:
  <<: *default
  database: scores_db

# For Heroku deployments:
# production:
#   <<: *default
#   url: <%= ENV['DATABASE_URL'] %>